# Generated by Django 5.0.1 on 2024-01-13 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japanese_text', models.CharField(max_length=255, unique=True)),
                ('english_translation', models.CharField(blank=True, max_length=255, null=True)),
                ('chinese_translation', models.CharField(blank=True, max_length=255, null=True)),
                ('thai_translation', models.CharField(blank=True, max_length=255, null=True)),
                ('korean_translation', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
