# Generated by Django 5.0.1 on 2024-01-14 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomTranslation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customtranslation',
            old_name='chinese_translation',
            new_name='cn_translation',
        ),
        migrations.RenameField(
            model_name='customtranslation',
            old_name='english_translation',
            new_name='en_translation',
        ),
        migrations.RenameField(
            model_name='customtranslation',
            old_name='korean_translation',
            new_name='kr_translation',
        ),
        migrations.RenameField(
            model_name='customtranslation',
            old_name='thai_translation',
            new_name='th_translation',
        ),
    ]
