# Generated by Django 5.0.1 on 2024-01-13 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='LabelSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50, unique=True)),
                ('dimensions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabelTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('nutrients', models.TextField()),
                ('other_info', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LabelManagement.country')),
                ('sizes', models.ManyToManyField(to='LabelManagement.labelsize')),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_info', models.TextField()),
                ('font_requirements', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('additional_requirements', models.TextField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LabelManagement.country')),
                ('label_sizes', models.ManyToManyField(to='LabelManagement.labelsize')),
            ],
        ),
    ]
