# Generated by Django 5.0.1 on 2024-01-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelManagement', '0002_nutrient_labeltemplate_company_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='amount',
            field=models.CharField(max_length=50),
        ),
    ]
