# Generated by Django 5.0.1 on 2024-01-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelManagement', '0004_remove_labeltemplate_nutrients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labeltemplate',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='expiry_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='instruction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
