# Generated by Django 5.0.1 on 2024-01-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelManagement', '0005_alter_labeltemplate_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labeltemplate',
            name='nutrients',
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='nutrients',
            field=models.ManyToManyField(to='LabelManagement.nutrient'),
        ),
    ]
