# Generated by Django 5.0.1 on 2024-01-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelManagement', '0006_remove_labeltemplate_nutrients_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='ImportCountry',
        ),
        migrations.RenameField(
            model_name='labeltemplate',
            old_name='country',
            new_name='import_country',
        ),
        migrations.RenameField(
            model_name='regulatoryrequirement',
            old_name='country',
            new_name='import_country',
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='content',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='labeltemplate',
            name='nutrients',
            field=models.ManyToManyField(blank=True, null=True, to='LabelManagement.nutrient'),
        ),
    ]
