# Generated by Django 5.0.1 on 2024-01-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelManagement', '0008_company_rename_content_labeltemplate_net_weight_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='barcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='country_of_origin',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='storage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labeltemplate',
            name='manufacturer',
            field=models.ManyToManyField(blank=True, null=True, to='LabelManagement.manufacturer'),
        ),
    ]
