# Generated by Django 5.0.1 on 2024-01-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LabelManagement', '0009_manufacturer_labeltemplate_barcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labeltemplate',
            old_name='manufacturer',
            new_name='manufacturers',
        ),
    ]
